Repository Juguetear/juguetear-web, pull requests merged in 2022-12, with the labels that each got.

#67 60 feat crear schemas para cargar el contenido de la home
  studio/deskStructure.ts
  studio/sanity.json
  studio/schemas/home-page.ts
  studio/schemas/link.ts
  studio/schemas/member.ts
  studio/schemas/schema.ts
Labels: enhancement :nail_care:, sanity :1234:

#68 61 feat se tienen que poder subir videos en el schema de juguetes
  components/VideoEmbedPreview.tsx
  package.json
  studio/schemas/schema.ts
  studio/schemas/toy.ts
  studio/schemas/video.ts
  studio/tsconfig.json
  yarn.lock
Labels: enhancement :nail_care:, sanity :1234:

#85 Sanity v3 migration
  .env.example
  .vscode/settings.json
  app/head.tsx
  app/layout.tsx
  app/studio/[[...index]]/head.tsx
  app/studio/[[...index]]/loading.tsx
  app/studio/[[...index]]/page.tsx
  deskStructure.ts
  next.config.js
  package.json
  sanity.cli.ts
  sanity.config.ts
  schemas/index.ts
  tsconfig.json
  yarn.lock
Labels: enhancement :nail_care:, configuration ⚙️, sanity :1234:

#103 Agrega a11y addon a Storybook
  .storybook/main.js
  package.json
  yarn.lock
Labels: enhancement :nail_care:, configuration ⚙️

#106 105 feat borrar la carpeta pages
  .storybook/preview.js
  app/globals.css
  app/head.tsx
  app/layout.tsx
  app/page.tsx
  pages/_app.tsx
  pages/_document.tsx
  tailwind.config.js
Labels: configuration ⚙️

#114 109 feat instalar testing library
  __tests__/app/home-page.test.tsx
  jest.config.js
  package.json
  yarn.lock
Labels: enhancement :nail_care:, configuration ⚙️

#107 86 feat crear schemas para la página colaborar con el proyecto
  deskStructure.ts
  schemas/index.ts
  studio/deskStructure.ts
  studio/schemas/collaborate.ts
  studio/schemas/schema.ts
Labels: enhancement :nail_care:
