Repository Juguetear/juguetear-web, pull requests merged in 2022-11, with the labels that each got.

#19 18 configurar sanity
  .env.example
  .gitignore
  README.md
  lib/client.ts
  package.json
  studio/.eslintrc
  studio/.npmignore
  studio/README.md
  studio/config/.checksums
  studio/config/@sanity/data-aspects.json
  studio/config/@sanity/default-layout.json
  studio/config/@sanity/default-login.json
  studio/config/@sanity/form-builder.json
  studio/config/@sanity/vision.json
  studio/package.json
  studio/plugins/.gitkeep
  studio/sanity.json
  studio/schemas/link.ts
  studio/schemas/member.ts
  studio/schemas/schema.ts
  studio/static/.gitkeep
  studio/static/favicon.ico
  studio/tsconfig.json
  studio/yarn.lock
  vercel.json
  yarn.lock
Labels: enhancement :nail_care:, configuration ⚙️

#28 Se agrega pre-commit hook para formatear codigo
  .husky/pre-commit
  package.json
  yarn.lock
Labels: enhancement :nail_care:, configuration ⚙️

#31 refactor: delete commit-msg hook
  .husky/commit-msg
Labels: bug :bug:

#29 Add font sizes
  styles/globals.css
  tailwind.config.js
Labels: configuration ⚙️

#33 Feat/vscode-workspace-settings
  .gitignore
  .vscode/extensions.json
  .vscode/settings.json
Labels: enhancement :nail_care:, configuration ⚙️

#38 Fix/extend-issue-template
  .github/ISSUE_TEMPLATE/BUG_FORM.yml
  .github/ISSUE_TEMPLATE/FEATURE_FORM.yml
  CONTRIBUTE.md
Labels: documentation :books:, enhancement :nail_care:

#43 39 [Feat]: Actualizar el schema para los miembros del equipo
  studio/schemas/member.ts
  studio/schemas/schema.ts
Labels: sanity :1234:

#44 41 [Feat]: crear schemas para los documentos/archivos
  studio/schemas/document.ts
  studio/schemas/documents.ts
  studio/schemas/schema.ts
Labels: sanity :1234:

#48 47 [Feat]: Mejorar schema member
  studio/schemas/link.ts
  studio/schemas/member.ts
  studio/schemas/schema.ts
Labels: sanity :1234:

#52 49 [Feat]: Migrar a la nueva versión de Yarn
  .gitignore
  .yarn/releases/yarn-3.2.4.cjs
  .yarnrc.yml
  package.json
  studio/package.json
  studio/schemas/schema.ts
  vercel.json
  yarn.lock
Labels: enhancement :nail_care:, configuration ⚙️

#57 56 feat permitir agregar texto alternativo a las imagenes en sanity
  studio/schemas/image.ts
  studio/schemas/member.ts
  studio/schemas/schema.ts
  studio/schemas/toy.ts
Labels: enhancement :nail_care:, a11y ♿
