Repository Juguetear/juguetear-web, pull requests merged in 2022-10, with the labels that each got.

#2 Crear archivo README
  CONTRIBUTE.md
  README.md
  REPLICATE.md
Labels: documentation

#9 feat: create template for PRs
  .github/pull_request_template.md
Labels: documentation :books:

#7 Instalar el stack base
  .eslintrc
  .gitignore
  .storybook/main.js
  .storybook/preview.js
  README.md
  components/Introduction.stories.mdx
  components/assets/code-brackets.svg
  components/assets/colors.svg
  components/assets/comments.svg
  components/assets/direction.svg
  components/assets/flow.svg
  components/assets/plugin.svg
  components/assets/repo.svg
  components/assets/stackalt.svg
  next.config.js
  package.json
  pages/_app.tsx
  pages/api/hello.ts
  pages/index.tsx
  postcss.config.js
  public/favicon.ico
  public/vercel.svg
  styles/globals.css
  tailwind.config.js
  tsconfig.json
  yarn.lock
Labels: enhancement :nail_care:

#15 Fix typo on readme
  README.md
Labels: documentation :books:

#16 Add requirement about WCAG 2.1 AA level
  CONTRIBUTE.md
Labels: documentation :books:

#20 build: installed eslint and setup script
  .eslintrc
  package.json
  yarn.lock
Labels: configuration ⚙️

#22 #14 Update README.md
  README.md
Labels: documentation :books:

#24 13-configurar-husky
  .gitignore
  .husky/commit-msg
  .husky/post-pull
  .husky/pre-commit
  package.json
  yarn.lock
Labels: enhancement :nail_care:, configuration ⚙️

#21 add: tailwind customizations and fonts
  pages/_document.tsx
  styles/globals.css
  tailwind.config.js
Labels: configuration ⚙️
