Repository Juguetear/juguetear-web, pull requests merged in 2023-03, with the labels that each got.

#156 139 feat Crear componente Checkbox
  app/globals.css
  components/Checkbox/Checkbox.stories.tsx
  components/Checkbox/Checkbox.test.tsx
  components/Checkbox/Checkbox.tsx
  tailwind.config.js
Labels: frontend, storybook, state: review needed

#175 140 crear componente button
  .gitignore
  components/Button/Button.stories.tsx
  components/Button/Button.test.tsx
  components/Button/Button.tsx
  components/assets/pdf.svg
  tailwind.config.js
Labels: frontend, storybook, state: in progress

#214 REFACTOR Video Schema
  schemas/index.ts
  schemas/video.ts
  studio/schemas/schema.ts
Labels: sanity :1234:, state: review needed

#199 refactor: create sanity vars file and use on each file
  lib/client.ts
  lib/sanity-variables.ts
  sanity.cli.ts
  sanity.config.ts
Labels: type: enhancement :nail_care:, sanity :1234:

#213 Refactor: Tag.stories.tsx
  components/Tag/Tag.stories.tsx
Labels: type: enhancement :nail_care:, storybook

#196 Refactorización de schema `link`
  schemas/index.ts
  schemas/link.ts
  studio/schemas/schema.ts
Labels: sanity :1234:

#225 WIP 197 - collaborate schema
  components/VideoEmbedPreview.tsx
  deskStructure.ts
  schemas/collaborate.ts
  schemas/index.ts
  schemas/video.ts
  studio/deskStructure.ts
  studio/schemas/schema.ts
Labels: sanity :1234:, state: review needed

#224 202 refactor solucionar errores en accordiontesttsx
  components/Accordion/Accordion.test.tsx
Labels: type: enhancement :nail_care:

#192 [FEAT] navbar component
  components/Navbar/Navbar.stories.tsx
  components/Navbar/Navbar.test.tsx
  components/Navbar/Navbar.tsx
Labels: frontend, storybook, state: review needed

#228 218 lint en Button.test.tsx
  components/Button/Button.test.tsx
Labels: type: enhancement :nail_care:

#229 203 Solucionar los errores de ESLint en ArrowButton.test.tsx
  components/ArrowButton/ArrowButton.test.tsx
Labels: type: enhancement :nail_care:

#226 148 eliminar el directorio studio también la config workspaces
  deskStructure.ts
  package.json
  studio/.eslintrc
  studio/.npmignore
  studio/README.md
  studio/config/.checksums
  studio/config/@sanity/data-aspects.json
  studio/config/@sanity/default-layout.json
  studio/config/@sanity/default-login.json
  studio/config/@sanity/form-builder.json
  studio/config/@sanity/vision.json
  studio/deskStructure.ts
  studio/package.json
  studio/plugins/.gitkeep
  studio/sanity.json
  studio/schemas/about.ts
  studio/schemas/accessibility-declaration.ts
  studio/schemas/characteristics_list.ts
  studio/schemas/document.ts
  studio/schemas/documents.ts
  studio/schemas/faq.ts
  studio/schemas/image.ts
  studio/schemas/member.ts
  studio/schemas/schema.ts
  studio/schemas/toy.ts
  studio/static/.gitkeep
  studio/static/favicon.ico
  studio/tsconfig.json
  yarn.lock
Labels: sanity :1234:, state: review needed

#231 Refactor: Tag.test.tsx
  components/Tag/Tag.test.tsx
Labels: type: enhancement :nail_care:

#235 ADD query ByTestId y REMOVE funcion getElementsByClassName
  components/IconChevron/IconChevron.test.tsx
  components/IconChevron/IconChevron.tsx
Labels: type: enhancement :nail_care:, state: review needed

#232 223 modificar los estilos
  components/Checkbox/Checkbox.tsx
Labels: type: enhancement :nail_care:, tailwind

#195 141 create Link component
  components/Link/Link.stories.tsx
  components/Link/Link.test.tsx
  components/Link/Link.tsx
Labels: frontend, storybook, state: review needed

#233 Refactor: TextArea.test.tsx
  components/TextArea/TextArea.test.tsx
Labels: type: enhancement :nail_care:, state: review needed

#238 #208 ADD query ByTestId, test para ver si esta el attr aria-hidden y REMOV…
  components/IconError/IconError.test.tsx
  components/IconError/IconError.tsx
Labels: state: review needed

#234 216 Solucionar errores de ESLint en Input.test.tsx
  components/Input/Input.test.tsx
Labels: type: enhancement :nail_care:, state: review needed

#244 Refactor test and fix lint errors
  components/Logo/Logo.test.tsx
Labels: type: enhancement :nail_care:

#227 bugfix/219 add PreviewProps & PreviewLayoutKey to VideoEmbedPreview
  components/VideoEmbedPreview.tsx
  schemas/video.ts
Labels: type: fix

#248 [Refactor] solucionar errores en Navbar.test.tsx
  components/Navbar/Navbar.test.tsx
Labels: type: fix

#261 Fix typo in README
  README.md
Labels: type: documentation :books:, state: review needed

#260 Move Prettier parameters from .vscode/settings.json to package.json
  .vscode/settings.json
  package.json
Labels: type: configuration ⚙️, state: review needed

#268 Agregando background dark a storybook logo
  components/Logo/Logo.stories.tsx
Labels: storybook

#256 [Update] NextJS, Sanity, Storybook dependencies
  .storybook/main.ts
  .storybook/preview.js
  .storybook/preview.tsx
  .vscode/settings.json
  app/layout.tsx
  app/studio/[[...index]]/head.tsx
  app/studio/[[...index]]/loading.tsx
  components/ArrowButton/ArrowButton.tsx
  components/Input/Input.tsx
  components/Link/Link.tsx
  components/TextArea/TextArea.tsx
  lib/font-variables.ts
  next.config.js
  package.json
  schemas/index.ts
  tailwind.config.js
  yarn.lock
Labels: type: enhancement :nail_care:, type: configuration ⚙️, type: fix
