Repository Juguetear/juguetear-web, pull requests merged in 2023-05, with the labels that each got.

#303 Refactor: migrate button stories to csf3
  components/Button/Button.stories.tsx
Labels: type: enhancement :nail_care:, storybook

#313 307 Feat: Crear componente Spinner
  components/Spinner/Spinner.stories.tsx
  components/Spinner/Spinner.test.tsx
  components/Spinner/Spinner.tsx
Labels: frontend, type: feature

#314 [Feat]: Create Team Member Component
  components/TeamMember/TeamMember.stories.tsx
  components/TeamMember/TeamMember.test.tsx
  components/TeamMember/TeamMember.tsx
  types/layout-schema-types.ts
Labels: frontend, type: feature

#297 Refactor/sanity-pages
  app/(website)/layout.tsx
  sanity.config.ts
  schemas/index.ts
  schemas/pages/layout.ts
  schemas/pages/page.ts
  schemas/shared/link.ts
Labels: sanity :1234:, state: in progress

#317 [Feat]: Added highlight prop to toy schema
  schemas/toy.ts
Labels: sanity :1234:

#316 [Feat]: Create Card Skeleton Loader
  components/CardSkeleton/CardSkeleton.stories.tsx
  components/CardSkeleton/CardSkeleton.test.tsx
  components/CardSkeleton/CardSkeleton.tsx
Labels: frontend, storybook, tailwind

#320 [Feat]: added validation for having a maximum of 2 pictures at the highlighted section
  schemas/pages/home-page.ts
Labels: sanity :1234:
