Repository Juguetear/juguetear-web, pull requests merged in 2023-02, with the labels that each got.

#146 [Refactor]: Mover y refactorizar el esquema characteristics_list
  schemas/characteristics_list.ts
  schemas/index.ts
Labels: sanity :1234:

#150 Docs/update structure
  .github/pull_request_template.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: documentation :books:

#145 fix: red hexa color
  tailwind.config.js
Labels: fix

#152 Título más inclusivo en schema `toy.ts`
  studio/schemas/toy.ts
Labels: sanity :1234:, a11y ♿

#134 133 refactor mover y refactorizar el esquema homepage
  .vscode/settings.json
  deskStructure.ts
  schemas/home-page.ts
  schemas/index.ts
  studio/deskStructure.ts
  studio/schemas/schema.ts
Labels: sanity :1234:

#166 feat: add under construction page
  __tests__/app/home-page.test.tsx
  app/page.tsx
Labels: documentation :books:, frontend

#165 Remover script `sanity`
  package.json
Labels: configuration ⚙️, sanity :1234:

#163 moved and refactor accesibility_declaration schema
  schemas/accessibility-declaration.ts
  schemas/index.ts
Labels: sanity :1234:

#138 75 feat crear componente accordion
  components/Accordion/Accordion.stories.tsx
  components/Accordion/Accordion.test.tsx
  components/Accordion/Accordion.tsx
  components/IconChevron/IconChevron.stories.tsx
  components/IconChevron/IconChevron.test.tsx
  components/IconChevron/IconChevron.tsx
  package.json
  tailwind.config.js
  yarn.lock
Labels: frontend, storybook

#168 [REFACTOR] image schema
  schemas/image.ts
  schemas/index.ts
Labels: configuration ⚙️, sanity :1234:

#170 153 refactor: add helper functions on characteristics schema
  schemas/characteristics.ts
  schemas/index.ts
  studio/schemas/schema.ts
Labels: sanity :1234:

#147 135 refactor: add helper functions on block schema
  README.md
  schemas/block.ts
  schemas/index.ts
  studio/schemas/accessibility-declaration.ts
  studio/schemas/block.ts
  studio/schemas/collaborate.ts
  studio/schemas/schema.ts
Labels: sanity :1234:

#171 #161 Tech Stack: Add links with docs and Remove sections Sanity/Storybook
  README.md
Labels: documentation :books:

#172 159-feat-agregar-al-staff-a-manu-y-tony
  README.md
Labels: documentation :books:, good first issue

#174 refactor: documents schema
  schemas/documents.ts
  schemas/index.ts
Labels: sanity :1234:

#173 fix(schemas): add title and remove options for image schema
  schemas/image.ts
  studio/schemas/image.ts
Labels: sanity :1234:, fix

#164 Use tsc files
  .husky/pre-commit
  package.json
  yarn.lock
Labels: configuration ⚙️

#180 [REFACTOR] Schema about, faq, member, toy
  schemas/about.ts
  schemas/faq.ts
  schemas/index.ts
  schemas/member.ts
  schemas/toy.ts
Labels: sanity :1234:

#189 Agregar propiedad `title` en schema `link.ts`
  studio/schemas/link.ts
Labels: bug :bug:, sanity :1234:

#183 Refactor/fonts
  .storybook/preview.js
  app/globals.css
  app/layout.tsx
  lib/font-variables.ts
  tailwind.config.js
Labels: enhancement :nail_care:, fix

#188 162 docs: add storybook & sanity to README.md
  README.md
Labels: documentation :books:

#194 Set up eslint plugins
  .eslintrc
  .husky/pre-commit
  .lintstagedrc.js
  package.json
  yarn.lock
Labels: type: configuration ⚙️
