Repository Juguetear/juguetear-web, pull requests merged in 2023-07, with the labels that each got.

#347 336 feat: Agregar sección 'Sobre el proyecto' y agregar componente PortableTxt
  app/(website)/acerca-de/page.tsx
Labels: type: enhancement :nail_care:, frontend, state: review needed

#352 [Feat]: Create Message schema
  schemas/index.ts
  schemas/message.ts
Labels: sanity :1234:

#339 322 bug error de caracteres ilegales en la ruta al hacer un commit de cambios en jestconfigjs
  .husky/pre-commit
  package.json
  yarn.lock
Labels: type: fix, dependencies
