Repository Juguetear/juguetear-web, pull requests merged in 2023-06, with the labels that each got.

#321 182 Feat: Crear componente Carousel
  components/ArrowButton/ArrowButton.tsx
  components/Card/Card.tsx
  components/Carousel/Carousel.stories.tsx
  components/Carousel/Carousel.test.tsx
  components/Carousel/Carousel.tsx
  jest.config.js
  package.json
  yarn.lock
Labels: frontend, state: review needed, type: feature

#315 Feat: Placeholder added
  components/Card/Card.tsx
  components/Logo/Logo.tsx
  tailwind.config.js
Labels: frontend, type: feature

#301 feat: create PortableTxt comp
  components/PortableTxt/PortableTxt.stories.tsx
  components/PortableTxt/PortableTxt.test.tsx
  components/PortableTxt/PortableTxt.tsx
  components/PortableTxt/mockedData.ts
  package.json
  schemas/index.ts
  schemas/pages/collaborate-page.ts
  schemas/shared/content.ts
  schemas/shared/images.ts
  schemas/shared/img.ts
  yarn.lock
Labels: sanity :1234:, frontend

#324 Update/dependencies
  app/(sanity)/studio/[[...index]]/Studio.tsx
  app/(sanity)/studio/[[...index]]/loading.tsx
  app/(sanity)/studio/[[...index]]/page.tsx
  components/Card/Card.tsx
  package.json
  yarn.lock
Labels: dependencies

#327 [Refactor]: Set 16:9 aspect ratio for Card Image
  components/Card/Card.tsx
Labels: type: enhancement :nail_care:, frontend, tailwind

#326 build: update node version
  package.json
Labels: type: enhancement :nail_care:

#328 Add about page queries and refactor types
  app/(website)/acerca-de/page.tsx
  components/ProjectParticipants/ProjectParticipants.stories.tsx
  components/ProjectParticipants/ProjectParticipants.tsx
  components/TeamMember/TeamMember.stories.tsx
  components/TeamMember/TeamMember.tsx
  lib/sanity-queries.ts
  types/about-page.ts
  types/home-page.ts
Labels: sanity :1234:

#337 318 Refactor: Ajustar los estilos en links del footer
  components/Footer/Footer.tsx
Labels: frontend
