Repository Juguetear/juguetear-web, pull requests merged in 2023-01, with the labels that each got.

#95 fix(readme): set the correct command for reload project successfully …
  README.md
Labels: documentation :books:

#123 116 feat actualizar templates para hacerlos mas concisos
  .github/ISSUE_TEMPLATE/BUG_FORM.yml
  .github/ISSUE_TEMPLATE/FEATURE_FORM.yml
  .github/pull_request_template.md
Labels: documentation :books:

#124 Bug: #121 Las fuentes inter y outfit no se ven en storybook
  .gitignore
  .storybook/main.js
  .storybook/preview.js
  components/Test/Test.stories.tsx
  components/Test/Test.tsx
  package.json
  yarn.lock
Labels: enhancement :nail_care:, storybook, fix

#115 71 crear componente state
  components/IconCheckmark/IconCheckmark.stories.tsx
  components/IconCheckmark/IconCheckmark.test.tsx
  components/IconCheckmark/IconCheckmark.tsx
  components/IconError/IconError.stories.tsx
  components/IconError/IconError.test.tsx
  components/IconError/IconError.tsx
  components/State/State.stories.tsx
  components/State/State.test.tsx
  components/State/State.tsx
  tailwind.config.js
Labels: frontend, storybook

#129 Distinguir entre los modos de color claro y oscuro para mostrar texto en el logo
  README.md
Labels: documentation :books:, a11y ♿

#122 [Bug]: Solucionar schema warning - video.ts #118
  components/VideoEmbedPreview.tsx
  studio/schemas/video.ts
Labels: bug :bug:, sanity :1234:

#125 90 feat crear componentes Tag y XMark
  components/IconError/IconError.tsx
  components/Tag/Tag.stories.tsx
  components/Tag/Tag.test.tsx
  components/Tag/Tag.tsx
  components/XMark/XMark.stories.tsx
  components/XMark/XMark.test.tsx
  components/XMark/XMark.tsx
  tailwind.config.js
Labels: frontend, storybook

#137 88-feat-crear-componente-Logo
  components/Logo/Logo.stories.tsx
  components/Logo/Logo.test.tsx
  components/Logo/Logo.tsx
  tailwind.config.js
Labels: frontend, storybook
