Repository Juguetear/juguetear-web, pull requests merged in 2023-04, with the labels that each got.

#269 Modifica los estilos hover del componente checkbox
  components/Checkbox/Checkbox.tsx
Labels: type: enhancement :nail_care:, frontend, tailwind

#271 204 - fix IconCkeckmark eslint errors && add data-testid property
  components/IconCheckmark/IconCheckmark.test.tsx
  components/IconCheckmark/IconCheckmark.tsx
Labels: type: enhancement :nail_care:

#273 [Docs] Se corrigió que el texto del logotipo de FrontendCafé fuera difícil de leer en temas claros
  README.md
Labels: type: documentation :books:, a11y ♿

#266 Refactor: Link.test.tsx
  components/Link/Link.test.tsx
Labels: type: enhancement :nail_care:

#243 Refactor: ArrowButton.stories.tsx
  components/ArrowButton/ArrowButton.stories.tsx
Labels: type: enhancement :nail_care:, storybook

#230 221 fix button storybook warnings
  components/Button/Button.stories.tsx
  components/assets/PDFIcon.tsx
  components/assets/pdf.svg
Labels: type: enhancement :nail_care:, state: inactive, state: review needed

#250 Fixing warnings from Link.Stories by renaming stories to match Pascal…
  components/Link/Link.stories.tsx
Labels: type: enhancement :nail_care:, storybook

#277 Feat/add layout (navbar, footer) schemas
  __tests__/app/home-page.test.tsx
  app/(sanity)/studio/[[...index]]/loading.tsx
  app/(sanity)/studio/[[...index]]/page.tsx
  app/(website)/layout.tsx
  app/(website)/page.tsx
  deskStructure.ts
  schemas/index.ts
  schemas/pages/layout.ts
  schemas/shared/relative-url.ts
  types/layout-schema-types.ts
Labels: type: configuration ⚙️, frontend, type: feature

#279 refactor: remove head component from layout
  app/layout.tsx
Labels: type: enhancement :nail_care:

#262 ADD componente Card disponible, no disponible y con imagen
  components/Card/Card.stories.tsx
  components/Card/Card.test.tsx
  components/Card/Card.tsx
Labels: frontend, storybook

#278 [Feat]: Create Footer Component
  components/Footer/Footer.stories.tsx
  components/Footer/Footer.test.tsx
  components/Footer/Footer.tsx
Labels: frontend, storybook

#285 fix: remove duplicate variables
  components/Link/Link.tsx
  schemas/index.ts
Labels: type: fix

#286 282 feat agregar componente navbar a appwebsitelayouttsx
  app/(website)/layout.tsx
  components/Navbar/Navbar.stories.tsx
  components/Navbar/Navbar.tsx
  types/layout-schema-types.ts
Labels: frontend

#288 [Feat:] Add Footer to the layout
  app/(website)/layout.tsx
  components/Footer/Footer.stories.tsx
  components/Footer/Footer.tsx
  types/layout-schema-types.ts
Labels: frontend

#287 [Feat]: Add config for image-sanity-url
  lib/client.ts
  next.config.js
Labels: sanity :1234:, type: feature

#289 Refactor PDFIcon.tsx
  components/assets/PDFIcon.tsx
Labels: type: enhancement :nail_care:

#295 Corrige el border-radius de los componentes input y textarea
  components/Input/Input.tsx
  components/TextArea/TextArea.tsx
Labels: frontend

#290 [Feat]: Arrange VideoEmbedPreview
  components/VideoEmbedPreview/VideoEmbedPreview.stories.tsx
  components/VideoEmbedPreview/VideoEmbedPreview.test.tsx
  components/VideoEmbedPreview/VideoEmbedPreview.tsx
  schemas/shared/video.ts
Labels: frontend, storybook

#284 [Feat]: Create Hero Component
  components/Hero/Hero.stories.tsx
  components/Hero/Hero.test.tsx
  components/Hero/Hero.tsx
  types/layout-schema-types.ts
Labels: frontend

#300 Remueve el objeto parameters de los componentes navBar y footer
  components/Footer/Footer.stories.tsx
  components/Navbar/Navbar.stories.tsx
Labels: type: enhancement :nail_care:, storybook
